services:
  garage:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    volumes:
      - /home/michael/garage/vols/garage.toml:/etc/garage.toml
      - /home/michael/garage/vols/meta:/var/lib/garage/meta
      - /home/michael/garage/vols/data:/var/lib/garage/data
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - /home/michael/garage/vols/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
      
  caddy:
    image: caddy-route53:latest
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/michael/caddy/conf:/etc/caddy
      - /home/michael/caddy/site:/srv
      - /home/michael/caddy/data:/data
      - /home/michael/caddy/config:/config
